#Server
server:
  port: 8094

#SpringBoot Logo
spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
